/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "OpenGLES2ExamplesApplication.h"

ScopedPointer<MainWindow> OpenGLES2ExamplesApplication::mainWindow(NULL);

OpenGLES2ExamplesApplication::OpenGLES2ExamplesApplication()
{
}

OpenGLES2ExamplesApplication::~OpenGLES2ExamplesApplication()
{
}

//==============================================================================
void OpenGLES2ExamplesApplication::initialise (const String& commandLine)
{
    // Do your application's initialisation code here..
    mainWindow = new MainWindow();
}

void OpenGLES2ExamplesApplication::shutdown()
{
    // Do your application's shutdown code here..
    mainWindow = 0;
}

ContentComponent* OpenGLES2ExamplesApplication::getContentComponent()
{
    return mainWindow->getContentComponent();
}

//==============================================================================
void OpenGLES2ExamplesApplication::systemRequestedQuit()
{
    quit();
}

//==============================================================================
const String OpenGLES2ExamplesApplication::getApplicationName()
{
    return "OpenGLES2Examples";
}

const String OpenGLES2ExamplesApplication::getApplicationVersion()
{
    return ProjectInfo::versionString;
}

bool OpenGLES2ExamplesApplication::moreThanOneInstanceAllowed()
{
    return true;
}

void OpenGLES2ExamplesApplication::anotherInstanceStarted (const String& commandLine)
{
    
}

//==============================================================================
// This macro generates the main() routine that starts the app.
START_JUCE_APPLICATION(OpenGLES2ExamplesApplication)
